# **Pandas** **Series**

**Creating** **a** **Pandas** **Series**

In [ ]:
# Creating an Empty Pandas Series

import pandas as pd
s = pd.Series()
print(s)

Series([], dtype: object)

In [ ]:
# Creating a Series from a NumPy Array

import numpy as np
import pandas as pd

data = np.array(['A', 'n', 'a', 'l', 'y', 's', 't'])
s = pd.Series(data)
print(s)

0    A
1    n
2    a
3    l
4    y
5    s
6    t
dtype: object

In [ ]:
# Creating a Series from a List

data = ['A', 'n', 'a', 'l', 'y', 's', 't']

s = pd.Series(data)
print(s)

0    A
1    n
2    a
3    l
4    y
5    s
6    t
dtype: object

In [ ]:
# Creating a Series from a Dictionary
dict1 = {'a':1, 'b':2, 'c':3}
s = pd.Series(dict1)
print(s)

a    1
b    2
c    3
dtype: int64

In [ ]:
# Creating a Series Using NumPy Functions

# Use NumPy function numpy.linspace() for creating evenly spaced numbers over a specified range.
import numpy as np
import pandas as pd

ser = pd.Series(np.linspace(1, 10, 5))
print(ser)

0     1.00
1     3.25
2     5.50
3     7.75
4    10.00
dtype: float64

In [ ]:
# Use Numpy Function numpy.random.randn() for generating random numbers from a normal distribution.

import numpy as np
import pandas as pd

ser = pd.Series(np.random.randn(10))
print(ser)

0    0.206100
1    1.599428
2    0.761548
3   -0.936561
4   -1.087016
5   -0.111718
6    0.823046
7   -1.272931
8    0.019736
9    0.204538
dtype: float64

In [ ]:
# Creating a Series Using range()

import pandas as pd
ser = pd.Series(range(5, 15))
print(ser)

0     5
1     6
2     7
3     8
4     9
5    10
6    11
7    12
8    13
9    14
dtype: int64

In [ ]:
# Creating a Series Using List Comprehension

import pandas as pd
ser = pd.Series(range(1,20, 3), index = [x for x in 'abcdefg'])
print(ser)

a     1
b     4
c     7
d    10
e    13
f    16
g    19
dtype: int64

**Access** **Elements** **of** **Pandas** **Series**

In [ ]:
# Accessing Element from Series with Position


# Accessing the First Element of Series
# import pandas and numpy
import pandas as pd
import numpy as np

# creating simple array
data = np.array(['A', 'n', 'a', 'l', 'y', 's', 't'])
ser = pd.Series(data)
# retrieve the first element
print(ser[0])

A

In [ ]:

# import pandas and numpy
import pandas as pd
import numpy as np
# creating simple array
data = np.array(['a', 'n', 'a', 'l', 'y', 's', 't'])

ser = pd.Series(data)
# retrieve the first element
print(ser[:5])

0    a
1    n
2    a
3    l
4    y
dtype: object

In [ ]:
# Accessing Last 10 Elements of Series
# import pandas and numpy
import pandas as pd
import numpy as np

# creating simple array
data = np.array(['d', 'a', 't', 'a', 'a', 'n',
                 'a', 'l', 'y', 's', 't', '3', '1'])
ser = pd.Series(data)

# retrieve the first element
print(ser[-10:])

3     a
4     a
5     n
6     a
7     l
8     y
9     s
10    t
11    3
12    1
dtype: object

In [ ]:
# importing pandas module
import pandas as pd

# making data frame
df = pd.read_csv('/nba.csv')

ser = pd.Series(df['Name'])
ser.head(10)

0    Avery Bradley
1      Jae Crowder
2     John Holland
3      R.J. Hunter
4    Jonas Jerebko
5     Amir Johnson
6    Jordan Mickey
7     Kelly Olynyk
8     Terry Rozier
9     Marcus Smart
Name: Name, dtype: object

In [ ]:
# Accessing First 5 Elements of Series in nba.csv File

ser[:5]

0    Avery Bradley
1      Jae Crowder
2     John Holland
3      R.J. Hunter
4    Jonas Jerebko
Name: Name, dtype: object

**Binary** **operations** **on** **Pandas** **DataFrame** **and** **Series**

In [ ]:
#                                           1. Arithmetic Operations on Series

# Adding Two Series
import pandas as pd
s1 = pd.Series([10, 20, 30], index=['a', 'b', 'c'])
s2 = pd.Series([1, 2, 3], index=['a', 'b', 'c'])

# Adding the two Series
result = s1 + s2
print(result)

a    11
b    22
c    33
dtype: int64

In [ ]:
#                                           2.Comparison Operations on Series

# Example: Checking Equality

import pandas as pd
s1 = pd.Series([10, 20, 30])
s2 = pd.Series([10, 25, 30])

# Comparing the two Series
result = s1 == s2
print(result)

0     True
1    False
2     True
dtype: bool

In [ ]:
#                                                       3.  Logical Operations on Series

# Logical AND on Series
import pandas as pd
s1 = pd.Series([True, False, True])
s2 = pd.Series([False, False, True])

# Applying logical AND
result = s1 & s2
print(result)

0    False
1    False
2     True
dtype: bool

In [ ]:
# Handling Missing Data in Binary Operations

# Arithmetic with NaN

import pandas as pd
df1 = pd.DataFrame({'A': [1, 2, None], 'B': [4, None, 6]})
df2 = pd.DataFrame({'A': [1, None, 3], 'B': [None, 5, 6]})

# Adding the DataFrames
result = df1 + df2
print(result)

     A     B
0  2.0   NaN
1  NaN   NaN
2  NaN  12.0

**Pandas** **Series** **Index**() **Methods**

In [ ]:

import pandas as pd

data = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])

# Accessing the index
print("Original Index:", data.index)

# Modifying the index
data.index = ['w', 'x', 'y', 'z']
print("Modified Series:\n", data)

Original Index: Index(['a', 'b', 'c', 'd'], dtype='object')
Modified Series:
 w    10
x    20
y    30
z    40
dtype: int64

In [ ]:
# Examples of Pandas Series Index() Attribute

# Example 1. Assigning Duplicate Index Labels
import pandas as pd
series = pd.Series(['New York', 'Chicago', 'Toronto', 'Lisbon'])

# Creating the row axis labels
series.index = ['City 1', 'City 1', 'City 3', 'City 3']
print(series)

City 1    New York
City 1     Chicago
City 3     Toronto
City 3      Lisbon
dtype: object

In [ ]:
# Example 2. Retrieving Index Labels
import pandas as pd
Date = ['1/1/2018', '2/1/2018', '3/1/2018', '4/1/2018']
idx_name = ['Day 1', 'Day 2', 'Day 3', 'Day 4']

sr = pd.Series(data = Date,index = idx_name)
print(sr.index)

Index(['Day 1', 'Day 2', 'Day 3', 'Day 4'], dtype='object')

In [ ]:
# Example 3. Resetting Index to Default
import pandas as pd

Date = ['1/1/2018', '2/1/2018', '3/1/2018', '4/1/2018']
idx_name = ['Day 1', 'Day 2', 'Day 3', 'Day 4']

sr = pd.Series(data = Date,        # Series Data
              index = idx_name   # Index
              )

# Resetting index to default
sr.reset_index(drop=True, inplace=True)
print(sr)

0    1/1/2018
1    2/1/2018
2    3/1/2018
3    4/1/2018
dtype: object